import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { API_BASE_URL } from '../config';
import { Link } from 'react-router-dom';
import { Star, Moon, Sun, Sparkles, ArrowLeft } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';
import './horoscopo.css';

const Horoscopo = () => {
    const { t, language } = useLanguage();
    const [predicciones, setPredicciones] = useState([]);
    const [cargando, setCargando] = useState(true);
    const [error, setError] = useState(null);

    const signos = [
        { nombre: 'Aries',       nombreEn: 'Aries',       icono: '♈' },
        { nombre: 'Tauro',       nombreEn: 'Taurus',      icono: '♉' },
        { nombre: 'Géminis',     nombreEn: 'Gemini',      icono: '♊' },
        { nombre: 'Cáncer',      nombreEn: 'Cancer',      icono: '♋' },
        { nombre: 'Leo',         nombreEn: 'Leo',         icono: '♌' },
        { nombre: 'Virgo',       nombreEn: 'Virgo',       icono: '♍' },
        { nombre: 'Libra',       nombreEn: 'Libra',       icono: '♎' },
        { nombre: 'Escorpio',    nombreEn: 'Scorpio',     icono: '♏' },
        { nombre: 'Sagitario',   nombreEn: 'Sagittarius', icono: '♐' },
        { nombre: 'Capricornio', nombreEn: 'Capricorn',   icono: '♑' },
        { nombre: 'Acuario',     nombreEn: 'Aquarius',    icono: '♒' },
        { nombre: 'Piscis',      nombreEn: 'Pisces',      icono: '♓' }
    ];

    useEffect(() => {
        const obtenerHoroscopo = async () => {
            setCargando(true);
            try {
                const res = await axios.get(`${API_BASE_URL}/api/horoscopo?lang=${language}`);
                setPredicciones(res.data);
                setCargando(false);
            } catch (err) {
                console.error("Error obteniendo el horóscopo:", err);
                setError(t('errorFallen'));
                setCargando(false);
            }
        };

        obtenerHoroscopo();
    }, [language]);

    if (cargando) return (
        <div className="horoscopo-container cargando">
            <div className="loader-astral"></div>
            <p>{t('horoscopoLoading')}</p>
        </div>
    );

    if (error) return (
        <div className="horoscopo-container error">
            <p>⚠️ {error}</p>
        </div>
    );

    return (
        <div className="horoscopo-container">
            <div className="horoscopo-nav">
                <Link to="/" className="btn-volver-bunker">
                    <ArrowLeft size={18} /> {t('horoscopoBack')}
                </Link>
            </div>
            
            <div className="horoscopo-header">
                <h1><Star className="icon-spin" /> {t('horoscopoTitle')} <Star className="icon-spin" /></h1>
                <p className="subtitle">{t('horoscopoSubtitle')}</p>
                <div className="header-decoration">
                    <Moon size={20} /> <Sparkles size={20} /> <Sun size={20} />
                </div>
            </div>

            {/* BLOQUE SEO — TEXTO INTRODUCTORIO VISIBLE E INDEXABLE */}
            <div className="horoscopo-seo-intro">
                {language === 'en' ? (
                    <>
                        <h2>Daily Horoscope — Astral Predictions Calibrated from the Bunker</h2>
                        <p>
                            Welcome to the <strong>Expediente X Granaíno Astral Observatory</strong>, where each day we synchronize
                            the twelve signs of the zodiac with the cosmic energies that influence our reality. Our horoscope is not
                            generated by chance: it draws on the ancient <strong>Western astrological tradition</strong> and the
                            positions of the planets as interpreted by our team of analysts, infused with that touch of mystery
                            that defines our bunker.
                        </p>
                        <p>
                            <strong>Astrology</strong> is one of humanity's oldest tools for self-knowledge. Dating back more than
                            4,000 years to Mesopotamia and later refined by the ancient Greeks, Egyptians, Arabs and Renaissance
                            scholars, astrology holds that the positions of the Sun, Moon, and planets at the moment of our birth
                            shape key aspects of our personality, our strengths and our weaknesses. Each of the <strong>twelve
                            zodiac signs</strong> corresponds to a specific segment of the sky and is associated with particular
                            characteristics, ruling planets and fundamental elements.
                        </p>
                        <p>
                            At Expediente X Granaíno we have always been drawn to the boundary between the known and the unknown.
                            The cosmos hides patterns that science has not yet fully deciphered, and astrology — whether you believe
                            in it or see it as a cultural and philosophical system — offers a fascinating map for navigating
                            uncertainty. Our daily predictions are updated every 24 hours and cover the twelve signs from
                            <strong> Aries to Pisces</strong>, offering guidance on love, work, health and general energy.
                        </p>
                        <h2>The Twelve Signs of the Zodiac and Their Influence</h2>
                        <p>
                            The zodiac wheel is divided into four elements: <strong>Fire</strong> (Aries, Leo, Sagittarius),
                            <strong> Earth</strong> (Taurus, Virgo, Capricorn), <strong>Air</strong> (Gemini, Libra, Aquarius)
                            and <strong>Water</strong> (Cancer, Scorpio, Pisces). Each element gives its signs a shared
                            energetic base that determines how they relate to the world, to emotions and to decision-making.
                            Understanding your sign is understanding one layer of your identity.
                        </p>
                        <p>
                            Below you will find today's prediction for each sign, generated fresh and updated daily.
                            Consult your sign, reflect on the message and, as we always say in the bunker:
                            <em> the truth is out there — sometimes written in the stars.</em>
                        </p>
                    </>
                ) : (
                    <>
                        <h2>Horóscopo Diario — Predicciones Astrales Calibradas desde el Búnker</h2>
                        <p>
                            Bienvenido al <strong>Observatorio Astral de Expediente X Granaíno</strong>, donde cada día sincronizamos
                            los doce signos del zodiaco con las energías cósmicas que influyen en nuestra realidad. Nuestro horóscopo
                            no se genera al azar: bebe de la antigua <strong>tradición astrológica occidental</strong> y de las
                            posiciones planetarias interpretadas por nuestro equipo de analistas, con ese toque de misterio que
                            define el búnker.
                        </p>
                        <p>
                            La <strong>astrología</strong> es una de las herramientas de autoconocimiento más antiguas de la humanidad.
                            Con más de 4.000 años de historia que arrancan en Mesopotamia y se refinan con los griegos, egipcios,
                            árabes y estudiosos del Renacimiento, la astrología sostiene que las posiciones del Sol, la Luna y los
                            planetas en el momento de nuestro nacimiento moldean aspectos clave de nuestra personalidad, nuestras
                            fortalezas y nuestras debilidades. Cada uno de los <strong>doce signos del zodiaco</strong> corresponde
                            a un segmento concreto del cielo y se asocia con características particulares, planetas regentes y
                            elementos fundamentales.
                        </p>
                        <p>
                            En Expediente X Granaíno siempre nos ha atraído la frontera entre lo conocido y lo desconocido.
                            El cosmos esconde patrones que la ciencia aún no ha descifrado del todo, y la astrología —tanto si
                            crees en ella como si la entiendes como sistema cultural y filosófico— ofrece un mapa fascinante
                            para navegar la incertidumbre. Nuestras predicciones diarias se actualizan cada 24 horas y cubren
                            los doce signos de <strong>Aries a Piscis</strong>, ofreciendo orientación sobre amor, trabajo,
                            salud y energía general.
                        </p>
                        <h2>Los Doce Signos del Zodiaco y Su Influencia</h2>
                        <p>
                            La rueda del zodiaco se divide en cuatro elementos: <strong>Fuego</strong> (Aries, Leo, Sagitario),
                            <strong> Tierra</strong> (Tauro, Virgo, Capricornio), <strong>Aire</strong> (Géminis, Libra, Acuario)
                            y <strong>Agua</strong> (Cáncer, Escorpio, Piscis). Cada elemento otorga a sus signos una base
                            energética compartida que determina cómo se relacionan con el mundo, las emociones y la toma de
                            decisiones. Entender tu signo es entender una capa de tu identidad.
                        </p>
                        <p>
                            A continuación encontrarás la predicción de hoy para cada signo, generada en fresco y actualizada
                            diariamente. Consulta el tuyo, reflexiona sobre el mensaje y, como siempre decimos en el búnker:
                            <em> la verdad está ahí fuera — a veces escrita en las estrellas.</em>
                        </p>
                    </>
                )}
            </div>

            <div className="signos-grid">
                {signos.map((s) => {
                    const displayName = language === 'en' ? s.nombreEn : s.nombre;
                    const prediccion = predicciones.find(
                        p => p.signo.toLowerCase() === s.nombre.toLowerCase()
                    )?.prediccion;
                    return (
                        <div key={s.nombre} className="signo-card">
                            <div className="signo-icono">{s.icono}</div>
                            <h3>{displayName.toUpperCase()}</h3>
                            <div className="divider"></div>
                            <p>{prediccion || t('horoscopoLoading')}</p>
                        </div>
                    );
                })}
            </div>

            {/* BLOQUE SEO — TEXTO INFORMATIVO POST-PREDICCIONES */}
            <div className="horoscopo-seo-footer">
                {language === 'en' ? (
                    <>
                        <h2>Astrology and the Paranormal: Connections We Study from the Bunker</h2>
                        <p>
                            At Expediente X Granaíno we have documented numerous testimonies of people who, during periods of
                            intense planetary alignment — such as <strong>full moons</strong>, <strong>solar eclipses</strong>
                            or <strong>significant planetary conjunctions</strong> — report anomalous experiences: unusual
                            sightings, vivid dreams, electromagnetic disturbances in their equipment or an overwhelming sense
                            of a paranormal presence. Coincidence? Perhaps. But at this bunker we do not dismiss any lead
                            without first analyzing it.
                        </p>
                        <p>
                            Ancient civilizations built their most important structures aligned with astral cycles. The
                            Alhambra in Granada, the Egyptian pyramids, Stonehenge and the megalithic sites scattered across
                            Andalusia all share one thing in common: their architects knew exactly where the stars would be.
                            It is no coincidence that many of the <strong>UFO sightings documented in Granada</strong> occur
                            precisely during the nights of greatest astral activity. We keep a record of this data and
                            cross-reference it with the sightings uploaded by our field agents.
                        </p>
                        <p>
                            Our horoscope is updated daily and is completely free. If you want to go deeper, explore the
                            rest of the bunker: the <strong>UFO case files</strong>, the <strong>paranormal news</strong>
                            section and our exclusive dossier on the <strong>Atarfe and Albolote sighting</strong> are
                            waiting for you. Remember: the sky holds more secrets than we dare imagine.
                        </p>
                    </>
                ) : (
                    <>
                        <h2>Astrología y Paranormal: Las Conexiones que Estudiamos desde el Búnker</h2>
                        <p>
                            En Expediente X Granaíno hemos documentado numerosos testimonios de personas que, durante períodos
                            de intensa actividad planetaria —como <strong>lunas llenas</strong>, <strong>eclipses solares</strong>
                            o <strong>conjunciones planetarias</strong> significativas—, reportan experiencias anómalas:
                            avistamientos inusuales, sueños vívidos, perturbaciones electromagnéticas en sus equipos o una
                            sensación abrumadora de presencia paranormal. ¿Coincidencia? Quizás. Pero en este búnker no
                            descartamos ninguna pista sin analizarla antes.
                        </p>
                        <p>
                            Las civilizaciones antiguas construyeron sus estructuras más importantes alineadas con los ciclos
                            astrales. La Alhambra de Granada, las pirámides egipcias, Stonehenge y los enclaves megalíticos
                            esparcidos por Andalucía tienen algo en común: sus constructores sabían exactamente dónde estarían
                            las estrellas. No es casualidad que muchos de los <strong>avistamientos OVNI documentados en
                            Granada</strong> ocurran precisamente durante las noches de mayor actividad astral. Llevamos
                            registro de estos datos y los cruzamos con los avistamientos subidos por nuestros agentes de campo.
                        </p>
                        <p>
                            Nuestro horóscopo se actualiza a diario y es completamente gratuito. Si quieres profundizar más,
                            explora el resto del búnker: los <strong>expedientes de casos OVNI</strong>, la sección de
                            <strong> noticias paranormales</strong> y nuestro dossier exclusivo sobre el <strong>avistamiento
                            de Atarfe y Albolote</strong> te esperan. Recuerda: el cielo esconde más secretos de los que
                            nos atrevemos a imaginar.
                        </p>
                    </>
                )}
            </div>

            <div className="horoscopo-footer">
                <p>{t('horoscopoSyncDate')}: {new Date().toLocaleDateString()}</p>
                <small>{t('horoscopoWarning')}</small>
            </div>
        </div>
    );
};

export default Horoscopo;
